export const CAST = {
  zavi:      { name: "Zavi",             img: "zavi-ask" },
  zayn:      { name: "Zayn",             img: "zayn-ask" },
  mum:       { name: "Mumma",            img: "mum-ask" },
  baker:     { name: "The baker",        img: "villager-baker", has: "has bread" },
  fisher:    { name: "The fisher",       img: "villager-fisher", has: "has fish" },
  keeper:    { name: "The shopkeeper",   img: "villager-shopkeeper", has: "keeps the shop" },
  sheller:   { name: "The shell trader", img: "villager-shell-trader", has: "has sea shells" },
  boy:       { name: "The coin boy",     img: "villager-coin-boy", has: "has one coin" },
  neighbour: { name: "The neighbour",    img: "villager-neighbour", has: "did not sign" }
};

export const WORDS = [
  { id:"coin", t:"COIN", emoji:"🪙", who:"boy",
    def:"A little round piece of metal money.",
    ask:"Look what I got for helping at the market! It is metal, it is round, and it goes clink when I drop it.",
    cloze:"A king put a lion's head on the very first one ever made. What is that round piece of metal money called?",
    clue:"Metal. Round. Flat. It goes clink when it lands." },
  { id:"note", t:"NOTE", emoji:"💵", who:"keeper",
    def:"Paper money.",
    ask:"Zavi handed me this today. It is only paper — but I took it, because it stands for her coins.",
    cloze:"Zavi handed the shopkeeper one piece of paper money. What do we call it?",
    clue:"It is paper money. It stands for coins that somebody is keeping safe for you." },
  { id:"shop", t:"SHOP", emoji:"🏪", who:"keeper",
    def:"A place where you go to buy things.",
    ask:"Zavi came in, put her money on my counter, and walked out with chocolate. Where was she standing?",
    cloze:"Zavi walked in with her money and walked out with chocolate. What is that place called?",
    clue:"You walk in, somebody stands behind the counter, you walk out with the thing you wanted." },
  { id:"shell", t:"SHELL", emoji:"🐚", who:"sheller",
    def:"The little sea shell people once used as money.",
    ask:"Long before there were coins, people by the sea paid for everything with these little shiny things.",
    cloze:"In the Maldives, people paid with a small shiny thing from the beach. What was it?",
    clue:"Small, smooth and shiny. It washes up on the beach. People once paid with them." },
  { id:"paper", t:"PAPER", emoji:"📄", who:"zavi",
    def:"Paper is what some money is made of — but paper on its own is not money.",
    ask:"I drew my own money and the shop said no! But mine is made of exactly the same stuff as Mumma's.",
    cloze:"The shopkeeper does not want it. He wants the agreement. What is your drawing made of?",
    clue:"Some money is made of it. But a piece of it on its own buys nothing at all." },
  { id:"money", t:"MONEY", emoji:"💰", who:"zavi",
    def:"Something everyone agreed we can use to buy things.",
    ask:"Mumma says everybody agreed that we can hand this over and get anything in the shop for it.",
    cloze:"Everybody agreed that it works, and that is why it buys things. What is it?",
    clue:"Everybody agreed to it. It can be metal, or paper, or a tap on a card." },
  { id:"deal", t:"DEAL", emoji:"🤲", who:"zayn",
    def:"When two people both say yes to a swap.",
    ask:"I said I would give you bread. You said you would give me eggs. We both said yes. So it is settled!",
    cloze:"Two people both said yes to the swap. What is that called?",
    clue:"Both people said yes. Now it is settled and neither one can change their mind." },
  { id:"swap", t:"SWAP", emoji:"🔄", who:"zayn",
    def:"To give one thing and get another.",
    ask:"I gave the fisher my shoes. He gave me his fish. No money went anywhere.",
    cloze:"Chicken Man tried all morning to give his chickens and get bread instead. What was he trying to do?",
    clue:"You hand over one thing and you get a different thing back." },
  { id:"pay", t:"PAY", emoji:"💳", who:"baker",
    def:"To give money for something.",
    ask:"The lady put her coins down on my counter and carried the bread home.",
    cloze:"You give the money and you get the thing. What are you doing?",
    clue:"You hand over money, and you take the thing home with you." },
  { id:"sign", t:"SIGN", emoji:"✍️", who:"neighbour",
    def:"To write your name to show you agree.",
    ask:"They all wrote their names at the bottom of the poster. Every one of them.",
    cloze:"Everyone put their name on the poster. What did every one of them have to do?",
    clue:"You write your own name at the bottom to show that you agree to it." },
  { id:"fake", t:"FAKE", emoji:"🎭", who:"zavi",
    def:"A copy that is not the real thing.",
    ask:"I bit this coin and it bent! A real one would never bend. Somebody made a copy to trick me.",
    cloze:"The boy bit the coin to check it. What was he worried it might be?",
    clue:"Somebody made a copy of the real thing, hoping nobody would notice." },
  { id:"trade", t:"TRADE", emoji:"⚖️", who:"fisher",
    def:"Swapping things with someone.",
    ask:"All morning: my fish for his rice, his rice for her rope, her rope for a net. Round and round.",
    cloze:"Shells and coins made it much easier to swap things all day long. What is all that swapping called?",
    clue:"Swapping things with people, over and over, all day long." },
  { id:"barter", t:"BARTER", emoji:"🔁", who:"zayn",
    def:"Swapping a thing for a thing, with no money at all.",
    ask:"I offered the baker my chicken and asked for bread. Not a single coin. Just my chicken for his bread.",
    cloze:"Swapping a thing for a thing, with no money at all. What is that called?",
    clue:"A thing for a thing. No coins, no notes, no money anywhere in it." },
  { id:"trust", t:"TRUST", emoji:"💛", who:"mum",
    def:"Believing someone will keep their promise.",
    ask:"Zavi gave the keeper every coin she had. He locked them in his box and gave her one piece of paper. Then she walked home smiling, with no coins at all.",
    cloze:"You leave your coins with somebody because you believe they will keep them safe. What is that called?",
    clue:"You leave something precious with somebody, because you believe they will look after it." },
  { id:"agreed", t:"AGREED", emoji:"🤝", who:"mum",
    def:"Everyone said yes.",
    ask:"Zavi said yes. Zayn said yes. Mumma said yes. Papa said yes. Not one of them said no.",
    cloze:"Nobody said yes to your paper. Not me, not Mumma, not the shop. What is the word for when everyone says yes?",
    clue:"Every single person said yes. That is why the paper works." },
  { id:"promise", t:"PROMISE", emoji:"🤞", who:"mum",
    def:"Something you said you would do, and you mean it.",
    ask:"The poster says: this paper is worth one chocolate. All four of them wrote their name on it. And they meant it.",
    cloze:"The paper says your money is safe, and they really mean it. What is that called?",
    clue:"You said you would do something, and you really mean to do it." }
];
